version: '3.1'

services:

    # nginx-proxy:
    #   image: jwilder/nginx-proxy:latest
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - //var/run/docker.sock:/tmp/docker.sock:ro

    nginx-proxy:
      # build:
      #   context: ../nginx-proxy
      image: shakdwipeea/nginx-proxy
      ports:
        - "80:80"
      volumes:
        - //var/run/docker.sock:/tmp/docker.sock:ro

    web:
      build: .
      # image: ep-clj-server
      depends_on:
        - db
      ports:
        - "7000:7000"
        - "8000:8000"
        - "7001:7001"
        - "8001:8001"
      environment:
        - VIRTUAL_HOST=content.entranceplus.in
        - VIRTUAL_PORT=8000
        - APP_VOIDWALKER=content.entranceplus.in:8000
        - APP_EP=threadstory.in:7000

    db:
      # build:
      #   context: .
      #   dockerfile: Dockerfile-postgres
      image: shakdwipeea/ep-database
      restart: always
      ports:
       - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: void
        POSTGRES_PASSWORD: walker
        POSTGRES_DB: voidwalker

volumes:
  pgdata:
    driver: local
